name: cDCGAN

seed: 42
data_path: . # input data path
batch_size: 128
output_dir: ./logs

nz: 100
ngf: 32
ndf: 32
nc: 10

nchannel: 1
lr_d: 0.0002
lr_g: 0.0005
beta1: 0.5
display_freq: 200
lr: 0.0001 # learning rate

eval_batch_size: 128 # evaluation batch size
num_workers: 4
max_epochs: 30
use_amp: false # use AMP (Automatic Mixed Precision)
debug: false
train_epoch_length: null
eval_epoch_length: null
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 1000
log_every_iters: 10
