cnf(t,axiom,[vient(X),-libre(X),-motive(X)]).
cnf(t,axiom,[libre(X),autreRdv(X),travail(X)]).
cnf(t,axiom,[-libre(X),-autreRdv(X)]).
cnf(t,axiom,[-libre(X),-travail(X)]).
cnf(t,axiom,[motive(X),-ennui(X),autreRdv(X)]).
cnf(t,axiom,[motive(X),-vient(Y),-vient(Z),-ami(X,Y),-ami(X,Z),eq(Y,Z)]).
cnf(t,axiom,[-motive(X),-vient(Y),-deteste(X,Y)]).
cnf(f,top_clause,[ami(a,c)]).
cnf(f,top_clause,[ami(c,a)]).
cnf(f,top_clause,[ami(a,b)]).
cnf(f,top_clause,[ami(c,b)]).
cnf(f,top_clause,[ami(d,b)]).
cnf(f,top_clause,[ami(d,a)]).
cnf(f,top_clause,[ami(e,a)]).
cnf(f,top_clause,[ami(e,c)]).
cnf(f,top_clause,[motive(b)]).
cnf(f,top_clause,[libre(b)]).
cnf(f,top_clause,[libre(c)]).
cnf(f,top_clause,[libre(d)]).
cnf(f,top_clause,[-travail(a)]).
cnf(f,top_clause,[-autreRdv(a)]).
cnf(f,top_clause,[travail(e)]).
cnf(f,top_clause,[ennui(c)]).
cnf(f,top_clause,[eq(X,X)]).
cnf(f,top_clause,[-eq(a,b)]).
cnf(f,top_clause,[-eq(a,c)]).
cnf(f,top_clause,[-eq(a,d)]).
cnf(f,top_clause,[-eq(a,e)]).
cnf(f,top_clause,[-eq(b,a)]).
cnf(f,top_clause,[-eq(b,c)]).
cnf(f,top_clause,[-eq(b,d)]).
cnf(f,top_clause,[-eq(b,e)]).
cnf(f,top_clause,[-eq(c,a)]).
cnf(f,top_clause,[-eq(c,b)]).
cnf(f,top_clause,[-eq(c,d)]).
cnf(f,top_clause,[-eq(c,e)]).
cnf(f,top_clause,[-eq(d,a)]).
cnf(f,top_clause,[-eq(d,b)]).
cnf(f,top_clause,[-eq(d,c)]).
cnf(f,top_clause,[-eq(d,e)]).
cnf(f,top_clause,[-eq(e,a)]).
cnf(f,top_clause,[-eq(e,b)]).
cnf(f,top_clause,[-eq(e,c)]).
cnf(f,top_clause,[-eq(e,d)]).
%cnf(f,top_clause,[deteste(c,d)]).

pf([vient(_),-vient(_)]<=1).
